set(_CATKIN_CURRENT_PACKAGE "track")
set(track_VERSION "0.0.0")
set(track_MAINTAINER "nn <nn@todo.todo>")
set(track_PACKAGE_FORMAT "1")
set(track_BUILD_DEPENDS "geometry_msgs" "roscpp" "rospy")
set(track_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "rospy")
set(track_BUILDTOOL_DEPENDS "catkin")
set(track_BUILDTOOL_EXPORT_DEPENDS )
set(track_EXEC_DEPENDS "geometry_msgs" "roscpp" "rospy")
set(track_RUN_DEPENDS "geometry_msgs" "roscpp" "rospy")
set(track_TEST_DEPENDS )
set(track_DOC_DEPENDS )
set(track_DEPRECATED "")